version: 2.1
orbs:
  node: circleci/node@3.0.0
  browser-tools: cicleci/browser-tools@1.0.0
workflows:
 testcafe-typescript_fron-back:
   jobs:
     tests:
       executor:
         name: node/default
     api-test:
           executor:
           name: node/default
           steps:
             - checkout
             - run: npm intall
             - run: npm run test

     - tests
     - api-test