version: 2.1
orbs:
  node: circleci/node@3.0.0
  browser-tools: circleci/browser-tools@1.0.0
jobs:
     ui-tests:
       executor:
         name: node/default
       steps:
         - checkout  
         - run: npm run test:functional:chrome:headless:with:report
     api-test:
        executor:
           name: node/default
        steps:
             - checkout
             - run: npm install
             - run: npm run test:api:report
workflows:
  testcafe-typescript_front-back:
    jobs:
      - ui-tests
      - api-test