version: 2.1
orbs:
  node: circleci/node@3.0.0
  browser-tools: circleci/browser-tools@1.0.0
  slack: circleci/slack@4.1.3
jobs:
     ui-tests:
       executor:
         name: node/default
       steps:
         - checkout  
         - run: npm install
         - run: npm run test:functional:browserstack
         - store_test_results:
             path: test-results
         - store_artifacts:
             path: test-results
   

     api-test:
        executor:
           name: node/default
        steps:
             - checkout
             - run: npm install
             - run: npm run test:api
             - slack/status:
                  fail_only: false
                  mentions: 'saora mx'
                  only_for_branches: master
                  webhook: '${SLACK_WEBHOOK}'
      
    

workflows:
  testcafe-typescript_front-back:
    jobs:
      - ui-tests
      - api-test